unstable_features = true
binop_separator = "Back"
condense_wildcard_suffixes = true
edition = "2018"
error_on_line_overflow = true
error_on_unformatted = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_layout = "Vertical"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
